package uaparser

var languages = []string{
	"af",
	"ar", "ar-ae", "ar-bh", "ar-dz", "ar-eg", "ar-iq", "ar-jo", "ar-kw", "ar-lb", "ar-ly", "ar-ma", "ar-om", "ar-qa", "ar-sa", "ar-sy", "ar-tn", "ar-ye", "ar-il",
	"be",
	"bg", "bg-bg",
	"ca", "ca-es",
	"cs", "cs-cz",
	"da", "da-dk",
	"de", "de-at", "de-ch", "de-li", "de-lu", "de-de",
	"el", "el-gr",
	"en", "en-au", "en-bz", "en-ca", "en-gb", "en-ie", "en-jm", "en-nz", "en-tt", "en-us", "en-za", "en_us", "en-sg", "en-in", "en-at", "en-en", "enus",
	"es", "es-es", "es-ar", "es-bo", "es-cl", "es-co", "es-cr", "es-do", "es-ec", "es-gt", "es-hn", "es-mx", "es-ni", "es-pa", "es-pe", "es-pr", "es-py", "es-sv", "es-uy", "es-ve", "es-us",
	"et",
	"eu",
	"fa",
	"fi", "fi-fi",
	"fo",
	"fr", "fr-be", "fr-ca", "fr-ch", "fr-lu", "fr-fr",
	"ga",
	"gd",
	"he", "he-il",
	"hi",
	"hr", "hr-hr",
	"hu", "hu-hu",
	"id",
	"is",
	"it", "it-ch", "it-it",
	"ja", "ja-jp",
	"ji",
	"ko", "ko-kr", "ko-us",
	"lt", "lt-lt",
	"lv",
	"mk",
	"ms",
	"mt",
	"nl", "nl-be", "nl-nl",
	"no", "no-no",
	"pl", "pl-pl",
	"pt", "pt-pt", "pt-br",
	"rm",
	"ro", "ro-mo", "ro-ro",
	"ru", "ru-ru", "ru-mo",
	"sb",
	"sk", "sk-sk",
	"sl",
	"sq",
	"sr",
	"sv", "sv-fi", "sv-se",
	"sx",
	"sz",
	"th", "th-th",
	"tn",
	"tr", "tr-tr",
	"ts",
	"uk", "uk-ua",
	"ur",
	"ve",
	"vi", "vi-vn",
	"xh",
	"zh", "zh-cn", "zh-hk", "zh-sg", "zh-tw",
	"zu",
}
